receivers:
  kubearmor_receiver:
    endpoint: ${env:KUBEARMOR_SERVICE}
    logfilter: ${env:LOGFILTER}

exporters:
  logging:
    verbosity: detailed
  # uncomment for exporting to Loki
  #loki:
  #  endpoint: "http://localhost:3100/loki/api/v1/push"

service:
  pipelines:
    logs:
      receivers:
        - kubearmor_receiver
      processors: []
      exporters:
        - logging
        # uncomment for exporting to Loki
        #- loki
