receivers:
  kubearmor_receiver:
    endpoint: ${env:KUBEARMOR_SERVICE?default=:32767}
    logfilter: ${env:LOGFILTER?default=all}

exporters:
  logging:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers:
        - kubearmor_receiver
      processors: []
      exporters:
        - logging
